### ISSUE TITLE
I think the archive is corrupt.

### ISSUE THREAD

**Issue by gto76** [zenon/NNGS_SGF_Archive#1]
Could you please check.

Thank you.

**Comment by zenon** [comment]
Hi gto76,

I'm very sorry that I only today see your request.

Are you sure you downloaded the right file? 103.303.290 bytes?

7zip handles it well for me.

z.

**Comment by gto76** [comment]
You're right, it works. I'm not sure why it didn't decompress it correctly, probably because I was decompressing in linux and maybe not using 7zip, I don't know.
Anyways, in  meantime I managed to download all the games from www.online-go.com server,
so I can send you a zip if you're interested.

cheers

**Comment by zenon** [comment]
That's cool!

online-go - games: As both of us currently go without EMail or anything, the easiest way would be to put them into a repository on your account.

Kind greetings, z.

**Comment by nerai** [comment]
Hello,
are those games from online-go.com still available?

**Comment by gto76** [comment]
I'll try to put them on Github today,
please remind me if I'll forget.

Cheers

2016-03-03 12:26 GMT+01:00 Sebastian notifications@github.com:

**Comment by gto76** [comment]
https://github.com/gto76/online-go-games

**Comment by nerai** [comment]
Great! Thank you.

**Comment by gto76** [comment]
I forgot to add this info to the documentation:
On 9.4.2014 the site recalibrated ratings of all players, by increasing them for around 10 ranks!
So basically all ratings before this day are totally off.

**Comment by zenon** [comment]
Very good! Thank you gto76!
